# Generated by Django 3.2.18 on 2024-02-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='owner_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
